# Generated by Django 4.2.7 on 2026-01-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_task_remuneration_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
